from __future__ import annotations

import argparse
import os
import shutil
import sys
import tempfile
from datetime import datetime
from pathlib import Path
from typing import Any

if __package__ in {None, ""}:
    sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from scripts.common import Issue, load_json, make_report, print_report, write_json
from scripts.pptx_runtime import build_presentation
from scripts.validate_project import validate_project


def _relative_or_absolute(path: Path, base_dir: Path) -> str:
    try:
        return path.resolve().relative_to(base_dir.resolve()).as_posix()
    except ValueError:
        return str(path.resolve()).replace("\\", "/")


def _output_path(
    project: dict[str, Any],
    base_dir: Path,
    explicit: Path | None,
) -> Path:
    if explicit is not None:
        return explicit if explicit.is_absolute() else (base_dir / explicit)
    configured = project.get("artifacts", {}).get("pptx")
    if isinstance(configured, str) and configured.strip():
        path = Path(configured)
        return path if path.is_absolute() else (base_dir / path)
    output_dir = project.get("project", {}).get("output_dir", "outputs/project")
    path = Path(str(output_dir)) / "deck.pptx"
    return path if path.is_absolute() else (base_dir / path)


def _declared_input_paths(
    project: dict[str, Any],
    base_dir: Path,
) -> set[Path]:
    candidates: list[str] = []
    source_files = project.get("project", {}).get("source_files", [])
    if isinstance(source_files, list):
        candidates.extend(item for item in source_files if isinstance(item, str))
    template_path = project.get("template", {}).get("path")
    if isinstance(template_path, str):
        candidates.append(template_path)
    assets = project.get("assets", [])
    if isinstance(assets, list):
        for asset in assets:
            if isinstance(asset, dict) and isinstance(asset.get("path"), str):
                candidates.append(asset["path"])
    resolved: set[Path] = set()
    for candidate in candidates:
        path = Path(candidate)
        resolved.add((path if path.is_absolute() else base_dir / path).resolve())
    return resolved


def _backup_existing(output: Path) -> Path | None:
    if not output.exists():
        return None
    timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    versions = output.parent / "versions"
    versions.mkdir(parents=True, exist_ok=True)
    candidate = versions / f"{output.stem}-{timestamp}{output.suffix}"
    counter = 1
    while candidate.exists():
        candidate = versions / f"{output.stem}-{timestamp}-{counter}{output.suffix}"
        counter += 1
    shutil.copy2(output, candidate)
    return candidate


def _save_atomic(presentation: Any, output: Path) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{output.stem}.",
        suffix=".pptx",
        dir=output.parent,
    )
    os.close(descriptor)
    temporary = Path(temporary_name)
    try:
        presentation.save(temporary)
        os.replace(temporary, output)
    finally:
        temporary.unlink(missing_ok=True)


def _update_project(
    project: dict[str, Any],
    *,
    output: Path,
    base_dir: Path,
) -> None:
    project.setdefault("artifacts", {})["pptx"] = _relative_or_absolute(output, base_dir)
    capabilities = project.setdefault("capabilities", {})
    capabilities["pptx_write"] = {
        "available": True,
        "provider": "python-pptx",
        "notes": "Editable PPTX was generated by the bundled fallback runtime.",
    }
    steps = project.setdefault("workflow", {}).setdefault("steps", {})
    steps["editable-pptx"] = {
        "status": "completed",
        "reason": "Generated by the bundled Python fallback runtime.",
    }
    if isinstance(steps.get("static-qa"), dict):
        steps["static-qa"] = {
            "status": "planned",
            "reason": "Run static QA on the newly generated PPTX.",
        }


def build_from_project(
    project_path: Path,
    *,
    base_dir: Path,
    output: Path | None = None,
    update_project: bool = False,
    preserve_existing: bool = True,
) -> dict[str, Any]:
    issues: list[Issue] = []
    try:
        project = load_json(project_path)
    except (OSError, ValueError) as exc:
        return make_report(
            "build_deck",
            [Issue("error", "input.read", str(exc), str(project_path))],
            project=str(project_path),
        )

    validation_issues = validate_project(project)
    issues.extend(validation_issues)
    if any(issue.severity == "error" for issue in issues):
        return make_report(
            "build_deck",
            issues,
            project=str(project_path),
            output=None,
            rendered_slides=[],
        )

    target = _output_path(project, base_dir, output).resolve()
    if target.suffix.lower() != ".pptx":
        issues.append(
            Issue(
                "error",
                "output.extension",
                "PPTX output path must end with .pptx",
                str(target),
            )
        )
    if target == project_path.resolve():
        issues.append(
            Issue(
                "error",
                "output.conflict",
                "PPTX output cannot overwrite project.json",
                str(target),
            )
        )
    if target in _declared_input_paths(project, base_dir):
        issues.append(
            Issue(
                "error",
                "output.input_conflict",
                "PPTX output cannot overwrite a declared source, template, or asset",
                str(target),
            )
        )
    if any(issue.severity == "error" for issue in issues):
        return make_report(
            "build_deck",
            issues,
            project=str(project_path),
            output=str(target),
            rendered_slides=[],
        )

    presentation, runtime_issues, rendered = build_presentation(
        project,
        base_dir=base_dir,
    )
    issues.extend(runtime_issues)
    if presentation is None or any(issue.severity == "error" for issue in issues):
        return make_report(
            "build_deck",
            issues,
            project=str(project_path),
            output=str(target),
            rendered_slides=rendered,
        )

    backup: Path | None = None
    try:
        if preserve_existing:
            backup = _backup_existing(target)
        _save_atomic(presentation, target)
        if update_project:
            _update_project(project, output=target, base_dir=base_dir)
            write_json(project_path, project)
    except (OSError, ValueError, TypeError) as exc:
        issues.append(
            Issue("error", "output.write", str(exc), str(target))
        )

    return make_report(
        "build_deck",
        issues,
        project=str(project_path),
        output=str(target),
        bytes=target.stat().st_size if target.is_file() else 0,
        backup=str(backup) if backup else None,
        update_project=update_project,
        rendered_slides=rendered,
    )


def main() -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Build a baseline editable PPTX from project.json using the bundled "
            "Python fallback runtime."
        )
    )
    parser.add_argument("project", type=Path)
    parser.add_argument(
        "--base-dir",
        type=Path,
        default=Path.cwd(),
        help="Resolve relative source, asset, and output paths from this directory.",
    )
    parser.add_argument("--output", type=Path)
    parser.add_argument("--report", type=Path)
    parser.add_argument("--update-project", action="store_true")
    parser.add_argument(
        "--no-backup",
        action="store_true",
        help="Do not preserve an existing PPTX under output/versions before replacement.",
    )
    args = parser.parse_args()
    report = build_from_project(
        args.project.resolve(),
        base_dir=args.base_dir.resolve(),
        output=args.output,
        update_project=args.update_project,
        preserve_existing=not args.no_backup,
    )
    if args.report:
        write_json(args.report, report)
    print_report(report)
    return 1 if report["summary"]["error"] else 0


if __name__ == "__main__":
    raise SystemExit(main())
